# Generated by Django 4.0.6 on 2022-08-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banner', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='Аватарка'),
        ),
    ]
