# Generated by Django 4.0.6 on 2022-08-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='01.08.2022', upload_to='image', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
