# Generated by Django 4.0.6 on 2022-08-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_rename_discription_advert_description_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='url',
            field=models.SlugField(default='None', max_length=60),
        ),
    ]
