# Generated by Django 4.0.6 on 2022-08-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advert_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='url',
        ),
    ]
